# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# schedules:
# - cron: '*/5 * * * *'
#   displayName: every 5 minutes midnight build
#   branches:
#     include:
#     - master
#   always: true

pool:
  name: amlpool

steps:
- script: echo Deploying Pipeline Schedule!
  displayName: '部署管道计划'

- bash: az --version
  displayName: 'Show Azure CLI version'

- script: |
    if ! command -v yq &> /dev/null
    then
        echo "yq could not be found, installing..."
        sudo snap install yq
    else
        echo "yq is already installed"
    fi
  displayName: 'Check and Install yq if not exists'
  continueOnError: true


- template: src/start-aml-schedule.yml
  parameters:
    serviceconnectionname: 'Azure-ARM-Dev'
