
trigger:
- master

schedules:
- cron: '*/5 * * * *'
  displayName: every 5 minutes midnight build
  branches:
    include:
    - main
  always: true

pool:
  name: amlpool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- template: src/deploy-registered.yml
  parameters:
    serviceconnectionname: 'Azure-ARM-Dev'
