
trigger:
- master

pool:
  name: amlpool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- template: src/deploy-endpoint.yml
  parameters:
    serviceconnectionname: 'Azure-ARM-Dev'
