$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline
jobs:
  sigle_job:
    command: >-
        python main.py
    environment: azureml:basic-env-scikit@latest
    compute: azureml:cluster1
