$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: cron_with_settings_job_schedule
display_name: Simple cron job schedule and setting
description: a simple hourly cron job schedule

trigger:
  type: cron
  expression: "*/3 * * * *"
  start_time: "2022-07-10T10:00:00" # optional - default will be schedule creation time
  time_zone: "China Standard Time" # optional - default will be UTC

tags: &schedule_tags
  schedule: cron_with_settings_schedule

create_job: 
  type: pipeline
  job: ./basic-pipeline-job.yml
  # job: azureml:simple-pipeline-job
  # runtime settings
  settings:
    default_compute: azureml:cluster1
    continue_on_step_failure: false
    force_rerun: true
    
  tags: 
    <<: *schedule_tags